// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxAuJn2u13oyQ9pzsKbt9aYac8cMejLyA',
    appId: '1:1082675554065:web:c49f5c276b4b302ec2ceb0',
    messagingSenderId: '1082675554065',
    projectId: 'rodasalonapp',
    authDomain: 'rodasalonapp.firebaseapp.com',
    storageBucket: 'rodasalonapp.firebasestorage.app',
    measurementId: 'G-ZFLG6XPK14',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdRzwBa5r6E1u-jMzkT_IpecyvtnFCqMM',
    appId: '1:1082675554065:android:c06a49052b823f99c2ceb0',
    messagingSenderId: '1082675554065',
    projectId: 'rodasalonapp',
    storageBucket: 'rodasalonapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaPDt5W-G9na17hxlE5zmkDI32GEX1PPY',
    appId: '1:1082675554065:ios:b33e3188471b19afc2ceb0',
    messagingSenderId: '1082675554065',
    projectId: 'rodasalonapp',
    storageBucket: 'rodasalonapp.firebasestorage.app',
    iosBundleId: 'com.example.rodaSalon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaPDt5W-G9na17hxlE5zmkDI32GEX1PPY',
    appId: '1:1082675554065:ios:b33e3188471b19afc2ceb0',
    messagingSenderId: '1082675554065',
    projectId: 'rodasalonapp',
    storageBucket: 'rodasalonapp.firebasestorage.app',
    iosBundleId: 'com.example.rodaSalon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxAuJn2u13oyQ9pzsKbt9aYac8cMejLyA',
    appId: '1:1082675554065:web:05da5f2e8c20ecaec2ceb0',
    messagingSenderId: '1082675554065',
    projectId: 'rodasalonapp',
    authDomain: 'rodasalonapp.firebaseapp.com',
    storageBucket: 'rodasalonapp.firebasestorage.app',
    measurementId: 'G-43YCD97YBN',
  );

}